# Generated by Django 2.2.5 on 2022-06-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_peopleinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='pub_date',
            field=models.DateField(null=True),
        ),
    ]
